const repositories = [
  {
    "id": "REP001",
    "name": "CUHK Research Data Repository",
    "url": "https://researchdata.cuhk.edu.hk/",
    "short": "CUHK RDR",
    "type": "Institutional / Generalist",
    "subjects": [
      "Other / General"
    ],
    "maxDatasetGB": 999999.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 15,
    "Q02_50to100gb": 15,
    "Q02_100to1000gb": 15,
    "Q02_1000gb_up": 15,
    "maxFileGB": 30.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": true,
    "code": false,
    "cuhk": true,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 10,
    "Q06_instituional_repo": true,
    "Q07_licenses": [
      "CC BY-NC"
    ],
    "best": "CUHK researchers with general research datasets",
    "limits": "File size 5 GB by default; adjustable upon request.",
    "notes": "Strong first option for CUHK-affiliated researchers when no discipline-specific repository is required."
  },
  {
    "id": "REP002",
    "name": "Figshare",
    "url": "https://figshare.com/",
    "short": "Figshare",
    "type": "Generalist",
    "subjects": [
      "Other / General"
    ],
    "maxDatasetGB": 20.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 10,
    "Q02_50to100gb": 10,
    "Q02_100to1000gb": 10,
    "Q02_1000gb_up": 10,
    "maxFileGB": 20.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": true,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 15,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY",
      "CC BY-NC"
    ],
    "best": "General datasets needing DOI and sharing options",
    "limits": "20 GB dataset limit.",
    "notes": "Useful general-purpose alternative."
  },
  {
    "id": "REP003",
    "name": "GitHub",
    "url": "https://github.com/",
    "short": "GitHub",
    "type": "Code / Generalist",
    "subjects": [
      "Software / Code"
    ],
    "maxDatasetGB": 5.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "maxFileGB": 0.1,
    "Q04_doi": false,
    "Q04_embargo": false,
    "Q04_private": true,
    "Q04_tiered_access": true,
    "code": true,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 15,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY"
    ],
    "best": "Software, code, collaboration, and version control",
    "limits": "Recommended maximum dataset size 5 GB.",
    "notes": "Best for code; pair with Zenodo if a DOI-archived software release is needed."
  },
  {
    "id": "REP004",
    "name": "OSF",
    "url": "https://osf.io/",
    "short": "OSF",
    "type": "Generalist / Project",
    "subjects": [
      "Other / General"
    ],
    "maxDatasetGB": 50.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 10,
    "maxFileGB": 5.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": true,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 15,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY",
      "CC BY-NC"
    ],
    "best": "Project-based research collaboration and general datasets",
    "limits": "50 GB public / 5 GB private.",
    "notes": "Good for project workflows and collaboration."
  },
  {
    "id": "REP005",
    "name": "Zenodo",
    "url": "https://zenodo.org/",
    "short": "Zenodo",
    "type": "Generalist",
    "subjects": [
      "Other / General"
    ],
    "maxDatasetGB": 50.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 15,
    "Q02_50to100gb": 10,
    "maxFileGB": 50.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": true,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 15,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY",
      "CC BY-NC"
    ],
    "best": "Multidisciplinary datasets needing DOI and embargo",
    "limits": "50 GB dataset limit.",
    "notes": "Popular general repository; useful alternative for general datasets."
  },
  {
    "id": "REP006",
    "name": "Cambridge Crystallographic Data Centre",
    "url": "https://www.ccdc.cam.ac.uk/",
    "short": "CCDC",
    "type": "Subject-specific",
    "subjects": [
      "Chemistry / Crystallography"
    ],
    "maxDatasetGB": 0.1,
    "Q02_100mb_down": 15,
    "maxFileGB": 0.05,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": false,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 10,
    "Q05_code_as_output": 0,
    "Q06_instituional_repo": false,
    "Q07_licenses": [],
    "best": "Crystallographic structure data",
    "limits": "Specific accepted formats only.",
    "notes": "Recommended first for crystallography because it is discipline-recognised."
  },
  {
    "id": "REP007",
    "name": "HEPData",
    "url": "https://www.hepdata.net/",
    "short": "HEPData",
    "type": "Subject-specific",
    "subjects": [
      "Particle Physics"
    ],
    "maxDatasetGB": 0.05,
    "Q02_100mb_down": 15,
    "maxFileGB": 0.01,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": true,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 10,
    "Q05_code_as_output": 15,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY",
      "CC BY-NC"
    ],
    "best": "Particle physics data",
    "limits": "Specific formats; YAML file limit applies.",
    "notes": "Recommended first for particle physics data."
  },
  {
    "id": "REP008",
    "name": "National Genomics Data Center",
    "url": "https://ngdc.cncb.ac.cn/",
    "short": "NGDC",
    "type": "Subject-specific",
    "subjects": [
      "Genomics"
    ],
    "maxDatasetGB": 9999.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 15,
    "Q02_50to100gb": 15,
    "Q02_100to1000gb": 15,
    "Q02_1000gb_up": 15,
    "maxFileGB": 20.0,
    "Q04_doi": false,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": false,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 15,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC BY",
      "CC BY-NC"
    ],
    "best": "Biological genomics data",
    "limits": "Size limit unknown in matrix.",
    "notes": "Recommended first for genomics data where suitable."
  },
  {
    "id": "REP009",
    "name": "RCSB PDB",
    "url": "https://www.rcsb.org/",
    "short": "RCSB PDB",
    "type": "Subject-specific",
    "subjects": [
      "Proteomics",
      "Structural Biology / Protein Structures"
    ],
    "maxDatasetGB": 999999.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 15,
    "Q02_50to100gb": 15,
    "Q02_100to1000gb": 15,
    "Q02_1000gb_up": 15,
    "maxFileGB": 999999.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": false,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 0,
    "Q05_code_as_output": 0,
    "Q06_instituional_repo": false,
    "Q07_licenses": [],
    "best": "Protein structure data",
    "limits": "Standard structural format parameters.",
    "notes": "Top priority specialized engine for macromolecular coordinates."
  },
  {
    "id": "REP010",
    "name": "ProteomeCentral",
    "url": "https://proteomecentral.proteomexchange.org/?view=datasets",
    "short": "ProteomeCentral",
    "type": "Subject-specific",
    "subjects": [
      "Proteomics"
    ],
    "maxDatasetGB": 0.015,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 15,
    "Q02_50to100gb": 15,
    "Q02_100to1000gb": 15,
    "Q02_1000gb_up": 15,
    "maxFileGB": 999999.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": false,
    "Q04_tiered_access": false,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 10,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY"
    ],
    "best": "Proteomics data",
    "limits": "15 MB for web interface upload only; DOI for complete submission.",
    "notes": "Use for proteomics where it matches submission needs."
  },
  {
    "id": "REP011",
    "name": "Mendeley Data",
    "url": "https://data.mendeley.com/",
    "short": "Mendeley Data",
    "type": "Generalist",
    "subjects": [
      "Other / General"
    ],
    "maxDatasetGB": 100.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 15,
    "Q02_50to100gb": 15,
    "maxFileGB": 100.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": true,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 15,
    "Q05_code_as_output": 10,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY",
      "CC BY-NC"
    ],
    "best": "General datasets up to 100 GB",
    "limits": "100 GB dataset and file limit.",
    "notes": "Good option when dataset size exceeds smaller generalist repositories."
  },
  {
    "id": "REP012",
    "name": "ScienceDB",
    "url": "https://www.scidb.cn/",
    "short": "ScienceDB",
    "type": "Generalist",
    "subjects": [
      "Other / General"
    ],
    "maxDatasetGB": 1000.0,
    "Q02_100mb_down": 15,
    "Q02_100mbto5gb": 15,
    "Q02_5to20gb": 15,
    "Q02_20to50gb": 15,
    "Q02_50to100gb": 15,
    "Q02_100to1000gb": 15,
    "Q02_1000gb_up": 10,
    "maxFileGB": 999999.0,
    "Q04_doi": true,
    "Q04_embargo": true,
    "Q04_private": true,
    "Q04_tiered_access": false,
    "code": false,
    "cuhk": false,
    "Q04_api": true,
    "Q05_code_with_data": 10,
    "Q05_code_as_output": 15,
    "Q06_instituional_repo": false,
    "Q07_licenses": [
      "CC0",
      "CC BY",
      "CC BY-NC"
    ],
    "best": "Very large general datasets",
    "limits": "Up to 1 TB.",
    "notes": "Strong option for very large interdisciplinary/general datasets."
  }
];
